server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: e2dmasterdata
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:5432/${POSTGRES_NAME:postgres}?currentSchema=${POSTGRES_SCHEMA:${spring.application.name}}&stringtype=unspecified&ApplicationName=${spring.application.name}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:1234}
  flyway:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:5432/${POSTGRES_NAME:postgres}
    schemas: ${POSTGRES_SCHEMA:${spring.application.name}}
    user: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:1234}
    baseline-on-migrate: true

management:
  context-path: /admin

eureka:
#  password: password
#  instance:
#    hostname: ${HOST:e2dmasterdata}
#    registryFetchIntervalSeconds: 3
#    leaseRenewalIntervalInSeconds: 5
#    statusPageUrlPath: ${management.context-path}/info
#    healthCheckUrlPath: ${management.context-path}/health
#    metadataMap:
#      instanceId: ${spring.application.name}
#      management:
#        context-path: ${management.context-path}
  client:
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOST:${HOST:clouddiscovery}}:${DISCOVERY_PORT:8761}/eureka/
